config/routes.rb
Rails.application.routes.draw do

  resources :file_tasks
  devise_for :users

  root 'front/greeting#index'

  namespace :admin do
    root 'welcome#index'
    resources :general_view do
      member do
        get :view_tasks
        delete :destroy_comment
      end
    end
    resources :work_groups do
      member do
        get :members_management
        post :add_member
        delete :destroy_member
      end
    end
    resources :tasks do
      resources :comments do
        delete :destroy_comment
      end
      member do
        get :tasks_management
        post :add_member
        post :adding_task
        patch :edit_task
        patch :update_status
        delete :destroy_comment
        delete :destroy_task
        delete :destroy_assigned_member
      end
    end
    resources :datasets do
      collection do
        get :users
        get :members
      end
    end
  end

  namespace :front do
    root 'greeting#index'
    resources :tasks do
      delete :destroy_comment
    end
    resources :work_groups do
      get :members_management, on: :member
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :name, :start_time, :end_time, :work_group_id, presence: true

  has_many :assigned_tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :file_tasks, dependent: :destroy
  belongs_to :work_group

  enum status: [:future, :in_progress, :done]

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < AdminController

  before_action :set_group, only: [:tasks_management, :adding_task, :edit_task, :add_member, :destroy_assigned_member]
  before_action :set_task, only: [:add_member, :destroy_comment, :destroy_assigned_member]

  def index
    @own_groups = WorkGroup.own_groups current_user
  end

  def tasks_management
    @new_task = Task.new
  end

  def adding_task
    @new_task = Task.new task_params
    @new_task.work_group_id = @group.id
    @new_task.save if @new_task.valid?
  end

  def destroy_task
    @group = WorkGroup.find_by id: params[:group_id]
    current_task = Task.find_by id: params[:task_id]
    current_task.destroy if current_task
  end

  def add_member
    member = UserHasGroup.find_by work_group_id: @group.id, user_id: params[:user_id]
    if member
      assigned_task = AssignedTask.new
      assigned_task.task_id = params[:task_id]
      assigned_task.user_has_group_id = member.id
      assigned_task.save
    end
    @task_id = params[:task_id]
  end

  def edit_task
    @group = WorkGroup.find_by id: params[:group_id]
    current_task = Task.find_by id: params[:task_id]
    current_task.update(task_params) if current_task.valid?
  end

  def update_status
    @file_task = FileTask.new
    @comment = Comment.new
    @task = Task.find_by id: params[:id]
    @group = @task.work_group
    work_group_hash = Hash.new
    ap work_group_hash
    work_group_hash["status"] = params[:status].to_i
    @task.update work_group_hash
    @future_tasks = @group.tasks.future
    @in_progress_tasks = @group.tasks.in_progress
    @done_tasks = @group.tasks.done
  end

  def destroy_comment
    comment = Comment.find_by id: params[:comment_id]
    comment.destroy unless comment.blank?
  end

  def destroy_assigned_member
    member = UserHasGroup.find_by work_group_id: @group.id, user_id: params[:user_id]
    if member
      assigned_task = AssignedTask.find_by task_id: params[:task_id], user_has_group_id: member.id
      assigned_task.destroy if assigned_task
    end
  end

  private

  def set_group
    @group = WorkGroup.find params[:id]
  end

  def set_task
    @task = Task.find_by id: params[:task_id]
  end

  def task_params
    params.require(:task).permit(:name, :description, :start_time, :end_time, :work_group_id)
  end

end

app/controllers/front/tasks_controller.rb
class Front::TasksController < FrontController

  before_action :set_tasks

  def index
    @future_tasks = @tasks.future
    @in_progress_tasks = @tasks.in_progress
    @done_tasks = @tasks.done
    @comment = Comment.new
    @file_task = FileTask.new
  end

  def destroy_comment
    comment = Comment.find_by id: params[:comment_id]
    comment.destroy unless comment.blank?
    @task = Task.find_by id: params[:task_id]
  end

  private

  def set_tasks
    @tasks = current_user.tasks
  end

end

app/views/admin/tasks/_current_tasks.html.erb
<% if group.tasks.blank? %>
	<h4>No task has been registered</h4>
<% else %>
	<div class="current-task">
		<h3>Registered tasks:</h3>
	</div>
	<table id="table-list-tasks">
		<% group.tasks.each do |t| %>
			<tr>
				<td><h4><%= t.name %></h4></td>
				<td class="edit-styles"><%= link_to "<i class='fa fa-user-plus'></i>".html_safe, '#', id:"add-member-task-button", class:"btn btn-primary", data: {toggle:"modal", target:"#modal-add-member-task-#{t.id}"} %></td>
        <td><%= render 'modal_add_member', task: t %></td>
        <td class="edit-styles"><%= link_to "<i class='fa fa-pencil-square-o'></i>".html_safe, '#' ,id:"edit-task-button", class:"btn btn-default", data: {toggle:"modal", target:"#modal-edit-task-#{t.id}"} %></td>
        <td><%= render 'modal_edit_task', task: t, group: group %></td>
				<td><%= link_to "<i class='fa fa-times'></i>".html_safe, {action: "destroy_task", task_id: t.id, group_id: group}, id:"delete-task-button", class:"btn btn-danger", data: { confirm: "#{t.name} will be removed of #{group.name}. Are you sure?" } , method: :delete, remote: true %></td>
			</tr>
			<script type="text/javascript">
			  var usersSource = new Bloodhound({
			    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
			    queryTokenizer: Bloodhound.tokenizers.whitespace,
			    remote: {
			      url: "/admin/datasets/members?query=%QUERY&group=<%= group.id %>",
			      wildcard: '%QUERY'
			    }
			  });
			  $('#search_member_typeahead_<%= t.id %>').typeahead(null, {
			    limit: 1000,
			    name: 'members',
			    display: 'full_name',
			    source: usersSource
			  });
			  $('#search_member_typeahead_<%= t.id %>').bind('typeahead:selected', function(obj, datum, name) {
			    $("#member-selected-<%= t.id %>").val(datum.id)
			  });
			  $('#modal-add-member-task-<%= t.id %>').on('hidden.bs.modal', function (e) {
				  $(this)
				    .find("input[type=text],input[type=date],textarea,select")
				       .val('')
				       .end()
				})
			</script>
		<% end %>
	</table>
<% end %>

app/views/admin/tasks/_list_tasks.html.erb
<div class="title-group">
  <%= group.name %>
	<button type="button" class="btn btn-primary style-b-new-task" data-toggle="modal" data-target="#modal-add-task">Create a new Task</button>
</div>
<div class="form-task">
  <%= render 'modal_new_task', new_task: @new_task, group: group %>
</div>
<div class="tasks-on-group">
  <%= render 'current_tasks', group: group %>
</div>

<script type="text/javascript">
	$('#modal-add-task').on('hidden.bs.modal', function (e) {
	  $(this)
	    .find("input[type=text],input[type=date],textarea,select")
	       .val('')
	       .end()
	})
</script>

app/views/admin/tasks/_members_on_task.html.erb
<% if User.assigned_members(task).empty? %>
  <b>No members has been assigned.</b>
<% else %>
  <b>Assigned to:</b>
  <br>
  <table id="members-table">
    <% User.assigned_members(task).each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <td style="margin-td"><%= link_to "<i class='fa fa-times'></i>".html_safe, {action: "destroy_assigned_member", task_id: task.id, group_id: group.id, user_id: a.id}, data: { confirm: "#{a.name} will be removed of: #{task.name}. Are you sure?" }, id:"delete-assigned-task", class:"btn btn-danger", method: :delete, remote: true %></td>
        <td class="margin-tdd">.</td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/admin/tasks/_modal_add_member.html.erb
<%= form_for [:admin , AssignedTask.new], url: add_member_admin_task_path(task_id: task.id), remote: true do |f| %>
  <div class="modal fade" id="modal-add-member-task-<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="myModalLabel">Adding member on task: <%= task.name %></h3>
        </div>
        <div class="modal-body">
          <table id="table-new-task">
            <tr>
              <td><%= label_tag 'Member' %></td>
              <td><input id="search_member_typeahead_<%= task.id %>" class="form-control typeahead" type="text" placeholder="Choose a User"></td>
              <%= text_field_tag :user_id, '', id:"member-selected-#{task.id}",class:"hide" %>
            </tr>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input type="submit" name="commit" value="Add Member" id="add-member-task" class="btn btn-primary">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/tasks/_modal_edit_task.html.erb
<%= form_for [:admin , task], url: edit_task_admin_task_path(group_id: group.id, task_id: task.id), remote: true do |f| %>
  <div class="modal fade" id="modal-edit-task-<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="myModalLabel">Editing task</h3>
        </div>
        <div class="modal-body">
          <table id="table-new-task">
            <tr>
              <td><%= f.label :name %></td>
              <td><%= f.text_field :name, class:"form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :description %></td>
              <td><%= f.text_area :description, class:"form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :start_time %></td>
              <td><%= f.date_field :start_time, class:"form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label :end_time %></td>
              <td><%= f.date_field :end_time, class:"form-control" %></td>
            </tr>
          </table>
          <div id="members-on-task-<%= task.id %>">
            <%= render 'members_on_task', task: task, group: group %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input type="submit" name="commit" value="Update Task" id="create-task" class="btn btn-primary" onclick="javascript:close_modal_edit_task(<%= task.id %>)">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/tasks/_modal_new_task.html.erb
<div class="modal fade" id="modal-add-task" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel">Creating new task</h3>
      </div>
        <%= form_for [:admin , new_task], url: adding_task_admin_task_path(group), remote: true do |f| %>
          <div class="modal-body">
            <table id="table-new-task">
              <tr>
                <td><%= f.label :name %></td>
                <td><%= f.text_field :name, class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :description %></td>
                <td><%= f.text_area :description, class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :start_time %></td>
                <td><%= f.date_field :start_time, class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :end_time %></td>
                <td><%= f.date_field :end_time, class:"form-control" %></td>
              </tr>
            </table>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input type="submit" name="commit" value="Create Task" id="create-task" class="btn btn-primary" onclick="javascript:close_modal_new_task()">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tasks/index.html.erb
<div class="col-md-1"></div>
<div class="col-md-4">
  <h1>Tasks Management</h1>
  <hr id="line-tasks">
  <% @own_groups.each do |own_group| %>
    <div class="task-selected">
      <h3><%= link_to own_group.name, '#', onclick:"javascript:view_tasks(#{own_group.id})" %></h3>
    </div>
    <table>
      <tr>
        <td><b>Description:</b></td>
        <td class="margin-td"><%= own_group.description %></td>
      </tr>
    </table>
    <br>
  <% end %>
</div>
<div id="detail-tasks" class="col-md-7">
  <div class="any-task-information">
    <div class="alert alert-info" role="alert">Click any group name to manage their tasks.</div>
  </div>
</div>