config/routes.rb
Rails.application.routes.draw do

  resources :file_tasks
  devise_for :users

  root 'front/greeting#index'

  namespace :admin do
    root 'welcome#index'
    resources :general_view do
      member do
        get :view_tasks
        delete :destroy_comment
      end
    end
    resources :work_groups do
      member do
        get :members_management
        post :add_member
        delete :destroy_member
      end
    end
    resources :tasks do
      resources :comments do
        delete :destroy_comment
      end
      member do
        get :tasks_management
        post :add_member
        post :adding_task
        patch :edit_task
        patch :update_status
        delete :destroy_comment
        delete :destroy_task
        delete :destroy_assigned_member
      end
    end
    resources :datasets do
      collection do
        get :users
        get :members
      end
    end
  end

  namespace :front do
    root 'greeting#index'
    resources :tasks do
      delete :destroy_comment
    end
    resources :work_groups do
      get :members_management, on: :member
    end
  end

end

app/views/layouts/admin/_nav.html.erb
<header>
	<nav class="be-grease large">
		<ul class="nav nav-pills nav-justified">
		  <li role="presentation">
        <%= link_to admin_root_path do %>
          <%= image_tag 'logo-twork.png', width: 150 %>
        <% end %>
      </li>
		  <li role="presentation" class="<%= 'active' if @controller == 'admin/work_groups' %>"><%= link_to "My Own Groups", admin_work_groups_path %></li>
      <li role="presentation" class="<%= 'active' if @controller == 'admin/tasks' %>"><%= link_to "Tasks", admin_tasks_path %></li>
      <li role="presentation" class="<%= 'active' if @controller == 'admin/general_view' %>"><%= link_to "General View", admin_general_view_index_path %></li>
      <li role="presentation"><%= link_to "User Portal", front_root_path %></li>
	  	<li role="presentation"><%= link_to "<i class='fa fa-power-off'></i>".html_safe, destroy_user_session_path, method: :delete %></li>
		</ul>
	</nav>
</header>