config/routes.rb
Rails.application.routes.draw do

  resources :file_tasks
  devise_for :users

  root 'front/greeting#index'

  namespace :admin do
    root 'welcome#index'
    resources :general_view do
      member do
        get :view_tasks
        delete :destroy_comment
      end
    end
    resources :work_groups do
      member do
        get :members_management
        post :add_member
        delete :destroy_member
      end
    end
    resources :tasks do
      resources :comments do
        delete :destroy_comment
      end
      member do
        get :tasks_management
        post :add_member
        post :adding_task
        patch :edit_task
        patch :update_status
        delete :destroy_comment
        delete :destroy_task
        delete :destroy_assigned_member
      end
    end
    resources :datasets do
      collection do
        get :users
        get :members
      end
    end
  end

  namespace :front do
    root 'greeting#index'
    resources :tasks do
      delete :destroy_comment
    end
    resources :work_groups do
      get :members_management, on: :member
    end
  end

end

app/models/file_task.rb
class FileTask < ActiveRecord::Base

  belongs_to :task
  belongs_to :user
  has_attached_file :image, styles: { medium: "800x600", square1: "100x100", square2: "200x200", modal: "600x400" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/file_tasks_controller.rb
class FileTasksController < ApplicationController

  layout 'front'
  before_action :set_file_task, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  def index
    @file_tasks = FileTask.all
  end

  def show
  end

  def new
    @file_task = FileTask.new
  end

  def edit
  end

  def create
    @file_task = FileTask.new file_task_params
    @file_task.save
  end

  def update
    if @file_task.update file_task_params
      redirect_to @file_task, notice: 'File task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @file_task.destroy
    redirect_to file_tasks_url, notice: 'File task was successfully destroyed.'
  end

  private

  def set_file_task
    @file_task = FileTask.find params[:id]
  end

  def file_task_params
    params.require(:file_task).permit(:image, :title, :task_id, :user_id)
  end

end

app/helpers/file_tasks_helper.rb
module FileTasksHelper
end

app/views/file_tasks/_form.html.erb
<%= form_for(@file_task) do |f| %>
  <div class="title-upload">
    <%= f.label :title %>
    <%= f.text_field :title, id:"title-image",class:"form-control" %>
  </div>
  <div class="image-upload">
    <%= f.file_field :image %>
  </div>
  <%= f.hidden_field :task_id, value: task.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit 'Upload File' ,class:"btn btn-primary" %>
  </div>
<% end %>

app/views/file_tasks/edit.html.erb
<h1>Editing File Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_task %> |
<%= link_to 'Back', file_tasks_path %>

app/views/file_tasks/index.html.erb
<h1>Listing File Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_tasks.each do |file_task| %>
      <tr>
        <td><%= file_task.title %></td>
        <td><%= image_tag file_task.image.url(:square2) %></td>
        <td><%= link_to 'Show', file_task %></td>
        <td><%= link_to 'Edit', edit_file_task_path(file_task) %></td>
        <td><%= link_to 'Destroy', file_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File task', new_file_task_path %>

app/views/file_tasks/new.html.erb
<h1>New File Task</h1>

<%= render 'form' %>

<%= link_to 'Back', file_tasks_path %>

app/views/file_tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @file_task.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @file_task.image.url() %>
</p>

<%= link_to 'Edit', edit_file_task_path(@file_task) %> |
<%= link_to 'Back', file_tasks_path %>